#!/bin/bash


true=":"
false="/bin/false"
success=0
failure=1



# TODO
# - Write help


usage() {
    local progname=`basename $0`

    cat <<EOM
    Usage
        $progname [{options}] [--] [{script} [{file}]]

    Options
        -h
            Show help.
EOM

    exit 1
}

die() {
    echo "$@" >&2
    exit 1
}

decho() {
    $DEBUG && echo "debug:" "$@" >&2
}

ALL_TEMPFILES=()
add_tempfiles() {
    [ $# = 0 ] && return
    for f in "$@"; do
        ALL_TEMPFILES=($ALL_TEMPFILES "$f")
    done
}

remove_all_tempfiles() {
    local x=$?
    for t in "${ALL_TEMPFILES[@]}"; do
        decho "removing tempfile $t..."
        rm -f "$t"
    done
    exit $x
}

get_tempfile() {
    local tempfile=`mktemp`
    add_tempfiles "$tempfile"
    echo "$tempfile"
}

run_script() {
    [ $# -ge 2 ] || die "invalid args"

    local script="$1"
    shift
    decho "script to run: [$script]"
    local result_file=`get_tempfile`
    decho "Vim result output = $result_file"

    # Let Vim run $script!
    # (`>/dev/null 2>&1` for truncating blank lines
    # which Vim outputs at startup...)
    $EX -c "so $script" \
        -c "write! $result_file" \
        -c 'qa!' \
        "$@" >/dev/null 2>&1

    # Output Vim result output.
    cat "$result_file"
}

build_ex_command() {
    EX="ex"
    if ! $EX_COMPATIBLE; then
        EX="$EX -N"
    fi
    if [ ! -z "$EX_IEXRC" ]; then
        EX="$EX -u $EX_IEXRC"
    fi
    if [ ! -z "$EX_VIMINFO" ]; then
        EX="$EX -i $EX_VIMINFO"
    fi
    if $EX_NOPLUGIN; then
        EX="$EX --noplugin"
    fi
    decho 'Build arguments with ex.' "$EX"
}

main() {
    # Remove all messed up tempfiles at exit...
    trap 'remove_all_tempfiles' EXIT

    build_ex_command

    local scripts
    scripts=()

    # Build script files from -e arguments
    # and add it to $scripts.
    local code s
    for code in "${EXECUTE_CODES[@]}"; do
        s=`get_tempfile`
        {
            echo "$code"
            echo 'write!'
            echo 'qall!'
        } >"$s"
        scripts=($scripts "$s")
    done

    # Get the script file.
    if [ $# -ne 0 ]; then
        scripts=($scripts "$1")
        shift
    fi

    # If no scripts run, run interactive ex (like Python).
    if [ "${#scripts[@]}" -eq 0 ]; then
        exec $EX
    fi

    # Run scripts.
    for s in "${scripts[@]}"; do
        run_script "$s" "$@"
    done
}


# Argument options
if [ -f "$HOME/.iexrc" ]; then
    EX_IEXRC="$HOME/.iexrc"
else
    EX_IEXRC="NONE"
fi
EX_COMPATIBLE="$false"
EX_NOPLUGIN="$true"
EX_VIMINFO=NONE
EXECUTE_CODES=()
DEBUG="$false"


while getopts Chdpu:i:e: opt; do
    case $opt in
        d) DEBUG="$true" ;;
        C) EX_COMPATIBLE="$true" ;;
        p) EX_NOPLUGIN="$false" ;;
        u) EX_IEXRC="$OPTARG" ;;
        i) EX_VIMINFO="$OPTARG" ;;
        e) EXECUTE_CODES=("${EXECUTE_CODES[@]}" "$OPTARG") ;;
        h) usage ;;
        ?) usage ;;
    esac
done
shift `expr $OPTIND - 1`


main "$@"
